/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIdentitiesRouteImport } from './routes/admin.identities'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as CoreResourceRouteImport } from './routes/core.$resource'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CoreResourceIdRouteImport } from './routes/core.$resource.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdentitiesRoute = AdminIdentitiesRouteImport.update({
  id: '/admin/identities',
  path: '/admin/identities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreResourceRoute = CoreResourceRouteImport.update({
  id: '/core/$resource',
  path: '/core/$resource',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreResourceIdRoute = CoreResourceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoreResourceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/identities': typeof AdminIdentitiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/core/$resource': typeof CoreResourceRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/core/$resource/$id': typeof CoreResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/identities': typeof AdminIdentitiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/core/$resource': typeof CoreResourceRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/core/$resource/$id': typeof CoreResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/identities': typeof AdminIdentitiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/core/$resource': typeof CoreResourceRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/core/$resource/$id': typeof CoreResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/identities'
    | '/admin/roles'
    | '/core/$resource'
    | '/api/auth/$'
    | '/core/$resource/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/identities'
    | '/admin/roles'
    | '/core/$resource'
    | '/api/auth/$'
    | '/core/$resource/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/identities'
    | '/admin/roles'
    | '/core/$resource'
    | '/api/auth/$'
    | '/core/$resource/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminIdentitiesRoute: typeof AdminIdentitiesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  CoreResourceRoute: typeof CoreResourceRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/identities': {
      id: '/admin/identities'
      path: '/admin/identities'
      fullPath: '/admin/identities'
      preLoaderRoute: typeof AdminIdentitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/$resource': {
      id: '/core/$resource'
      path: '/core/$resource'
      fullPath: '/core/$resource'
      preLoaderRoute: typeof CoreResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/$resource/$id': {
      id: '/core/$resource/$id'
      path: '/$id'
      fullPath: '/core/$resource/$id'
      preLoaderRoute: typeof CoreResourceIdRouteImport
      parentRoute: typeof CoreResourceRoute
    }
  }
}

interface CoreResourceRouteChildren {
  CoreResourceIdRoute: typeof CoreResourceIdRoute
}

const CoreResourceRouteChildren: CoreResourceRouteChildren = {
  CoreResourceIdRoute: CoreResourceIdRoute,
}

const CoreResourceRouteWithChildren = CoreResourceRoute._addFileChildren(
  CoreResourceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminIdentitiesRoute: AdminIdentitiesRoute,
  AdminRolesRoute: AdminRolesRoute,
  CoreResourceRoute: CoreResourceRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
