-- Runtime authentication/authorization grants.
-- Executed by the migration owner, not by application roles.

GRANT USAGE ON SCHEMA identity
TO slgs_cms, slgs_sims;

-- Better Auth identity + credential tables.
GRANT SELECT, INSERT, UPDATE
ON identity."user",
   identity.account
TO slgs_cms, slgs_sims;

-- Authentication session lifecycle.
GRANT SELECT, INSERT, UPDATE, DELETE
ON identity.session
TO slgs_cms, slgs_sims;

-- Verification records used by authentication flows.
GRANT SELECT, INSERT, UPDATE, DELETE
ON identity.verification
TO slgs_cms, slgs_sims;

-- 2FA records, if enabled by the application.
GRANT SELECT, INSERT, UPDATE, DELETE
ON identity.two_factor
TO slgs_cms, slgs_sims;

-- Application authorization is read-only for runtime applications.
GRANT SELECT
ON identity.application_membership,
   identity.role_assignment,
   identity.role_definition
TO slgs_cms, slgs_sims;

-- CMS/SIMS applications should not manipulate privileged
-- bootstrap or platform audit records.
--
-- security_audit_event is intentionally omitted here.
-- privileged_bootstrap is intentionally omitted here.

-- Sequence privileges are not required because the identity
-- schema currently uses text IDs generated by the application.
